stages:
      info:
            cmd: PYTHONPATH=. python pipelines/info.py
            wdir: ../
            deps:
                  - pipelines/info.py
                  - data-raw/gov_emissions.xlsx
            outs:
                  - data/info/passenger_vehicles_info.csv:
                          cache: false
                  - data/info/air_travel_info.csv:
                          cache: false
      # prepare:
      #       cmd: PYTHONPATH=. python pipelines/prepare.py
      #       wdir: ../
      #       deps:
      #             - pipelines/prepare.py
      #             - data/transformed
      #       outs:
      #             - data/prepped/emission_factor_catalogue.csv:
      #                     cache: false
      flat_transform:
            cmd: PYTHONPATH=. python pipelines/flat_transform.py
            wdir: ../
            deps:
                  - pipelines/flat_transform.py
                  - data-raw/emission_factors_flat_file.xlsx
            outs:
                  - data/emission_factors.csv:
                        cache: false